apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-image
        image: zielony/frontend
        imagePullPolicy: Always
        env: 
        - name: "REACT_APP_ENDPOINT"
          valueFrom:
            configMapKeyRef:
              name: {{.Values.configMap.name}} 
              key: externalSvc
        ports:
        - containerPort: {{ .Values.port }}