apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: hub
  name: hub-rte
spec: 
  host:
  port:
    targetPort: {{.Values.hub.port}}
  to:
    kind: Service
    name: hub-svc
    weight: 100
  wildcardPolicy: None